bert_hidden_dim: 768
bert_pretrain: true
drop_ratio: 0.0
gin_hidden_dim: 300
gin_num_layers: 5
graph_pooling: sum
graph_self: true
lr: 0.0001
projection_dim: 256
temperature: 0.1
weight_decay: 1.0e-05
